# NOTE: This docker file supports Postgresql V14.*. Replace all literal values
# of 14 below with 12, 13 to use other versions of Postgresql.

# https://hub.docker.com/_/postgres/
FROM postgres:15.1


# # Intall pg_cron extension
# RUN apt update
# RUN apt -y install postgresql-14-cron
# RUN echo "shared_preload_libraries = 'pg_cron'" >> /usr/share/postgresql/14/postgresql.conf.sample

# # NOTE: Database name is postgres. If you change the database name, in 
# # .env/POSTGRES_DB=postgres or .env.local/POSTGRES_DB=postgres then you
# # will also need to change the database name here.
# RUN echo "cron.database_name = 'postgres'" >> /usr/share/postgresql/14/postgresql.conf.sample


# # Install http extension
# # https://github.com/pramsey/pgsql-http#installation
# # see https://tech.mizuki.io/post/3/
# # https://hub.docker.com/r/supabase/postgres
# RUN apt -y install postgresql-server-dev-14 libcurl4-openssl-dev make g++

# RUN apt -y install build-essential git

# RUN cd /tmp; git clone https://github.com/pramsey/pgsql-http.git; cd pgsql-http; make; make install
