# NOTE: This docker file supports Postgresql V14.*. Replace all literal values
# of 14 below with 12, 13 to use other versions of Postgresql.

# https://hub.docker.com/_/postgres/
FROM postgres:14.1


# # Intall pg_cron extension
# RUN apt update
# RUN apt -y install postgresql-14-cron
# RUN echo "shared_preload_libraries = 'pg_cron'" >> /usr/share/postgresql/14/postgresql.conf.sample

# # NOTE: Database name is postgres. If you change the database name, in 
# # .env/POSTGRES_DB=postgres or .env.local/POSTGRES_DB=postgres then you
# # will also need to change the database name here.
# RUN echo "cron.database_name = 'postgres'" >> /usr/share/postgresql/14/postgresql.conf.sample


# # Install http extension
# RUN apt -y install build-essential git

# # for curl-config
# RUN apt -y install libcurl4-openssl-dev
# RUN apt -y install libpq-dev

# # We are prompted with:
# #   What do you want to do about modified configuration file createcluster.conf? 
# #   We prefer 2. keep the local version currently installed
# # but added noninteractive to stop prompt and hopefully Prefer 2 is selected
# # (note: when using apt -y install dialog, the default was 2)
# RUN DEBIAN_FRONTEND=noninteractive apt -y install postgresql-server-dev-all
# RUN cd /tmp; git clone https://github.com/pramsey/pgsql-http.git; cd pgsql-http; make; make install
